package antileak.base.api.storages.implement.helpertstorages.enumvar;

import com.jcraft.jorbis.Block;
import antileak.base.client.modules.impl.combat.*;
import antileak.base.client.modules.impl.misc.*;
import antileak.base.client.modules.impl.movement.*;
import antileak.base.client.modules.impl.player.*;

import antileak.base.client.modules.impl.render.*;
public interface ModuleRewords {
    AirStuck airStuck = AirStuck.INSTANCE;
    Arrows arrows = Arrows.INSTANCE;
    Aura aura = Aura.INSTANCE;
    AntiBot antibot = AntiBot.INSTANCE;
    AutoAccept autoAccept = AutoAccept.INSTANCE;
    AutoArmor autoArmor = AutoArmor.INSTANCE;
    AutoForest autoForest = AutoForest.INSTANCE;
    LeaveTracker leavetracker = LeaveTracker.INSTANCE;
    AutoBuy autoBuy = AutoBuy.INSTANCE;
    AutoDuel autoDuel = AutoDuel.INSTANCE;
    AutoEat autoEat = AutoEat.INSTANCE;
    AutoLeave autoLeave = AutoLeave.INSTANCE;
    AutoExplosion autoExplosion = AutoExplosion.INSTANCE;
    NameProtect nameProtect = NameProtect.INSTANCE;
    Chams chams = Chams.INSTANCE;
    ClientSounds clientSounds = ClientSounds.INSTANCE;
    AutoTool autoTool = AutoTool.INSTANCE;
    AutoTotem autoTotem = AutoTotem.INSTANCE;
    AutoTrap autoTrap = AutoTrap.INSTANCE;
    BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
    ClickPearl clickPearl = ClickPearl.INSTANCE;
    Cosmetics cosmetics = Cosmetics.INSTANCE;
    Cubes cubes = Cubes.INSTANCE;
    KillEffect killEffect = KillEffect.INSTANCE;
    BlockESP blockesp = BlockESP.INSTANCE;
    ElytraBoost elytraBoost = ElytraBoost.INSTANCE;
    ElytraExploit elytraExploit = ElytraExploit.INSTANCE;
    GrimExploit grimExploit = GrimExploit.INSTANCE;
    ElytraMotion elytraMotion = ElytraMotion.INSTANCE;
    ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
    ElytraTarget elytraTarget = ElytraTarget.INSTANCE;
    EntityESP entityESP = EntityESP.INSTANCE;
    FreeCam freeCam = FreeCam.INSTANCE;
    FullBright fullBright = FullBright.INSTANCE;
    GrimGlide grimGlide = GrimGlide.INSTANCE;
    HighJump highJump = HighJump.INSTANCE;
    HitBubbles hitBubbles = HitBubbles.INSTANCE;
    Interface interfaceModule = Interface.INSTANCE;
    InterpolateF5 interpolateF5 = InterpolateF5.INSTANCE;
    InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
    ItemAim itemAim = ItemAim.INSTANCE;
    ItemScroller itemScroller = ItemScroller.INSTANCE;
    ItemRelease itemRelease = ItemRelease.INSTANCE;
    JumpCircle jumpCircle = JumpCircle.INSTANCE;
    KTLeave kTLeave = KTLeave.INSTANCE;
    LockSlot lockSlot = LockSlot.INSTANCE;
    NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
    NoPush noPush = NoPush.INSTANCE;
    NoVelocity noVelocity = NoVelocity.INSTANCE;
    NoVignette noVignette = NoVignette.INSTANCE;
    NoControllerWeb noControllerWeb = NoControllerWeb.INSTANCE;
    NoWeb noWeb = NoWeb.INSTANCE;
    PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
    Particle particle = Particle.INSTANCE;
    ParticularWater particularWater = ParticularWater.INSTANCE;
    Pets pets = Pets.INSTANCE;
    Projectile projectile = Projectile.INSTANCE;
    FireworkESP fireworkESP = FireworkESP.INSTANCE;
    FastExp fastExp = FastExp.INSTANCE;
    Removals removals = Removals.INSTANCE;
    RPSpoofer rPSpoofer = RPSpoofer.INSTANCE;
    SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
    ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
    ShaderHands shaderHands = ShaderHands.INSTANCE;
    ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
    Sonar sonar = Sonar.INSTANCE;
    Sprint sprint = Sprint.INSTANCE;
    SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
    TargetESP targetESP = TargetESP.INSTANCE;
    TargetPearl targetPearl = TargetPearl.INSTANCE;
    TotemAngel totemAngel = TotemAngel.INSTANCE;
    TotemParticles totemParticles = TotemParticles.INSTANCE;
    TapeMouse tapeMouse = TapeMouse.INSTANCE;
    TpsSync tpsSync = TpsSync.INSTANCE;
    ViewModel viewModel = ViewModel.INSTANCE;
    WorldTweaks worldTweaks = WorldTweaks.INSTANCE;
    AutoSwap autoSwap = AutoSwap.INSTANCE;
    AimBot aimBot = AimBot.INSTANCE;
    NoSlow noSlow = NoSlow.INSTANCE;
    ScoreboardHP scoreboardHP = ScoreboardHP.INSTANCE;
    PotionTracker potionTracker = PotionTracker.INSTANCE;
    AntiThorns antithorns = AntiThorns.INSTANCE;
    ServerHelper serverHelper = ServerHelper.INSTANCE;
    LootTracker lootTracker = LootTracker.INSTANCE;
    HitMarker hitMarker = HitMarker.INSTANCE;
    Trails trails = Trails.INSTANCE;
    Trajectories trajectories = Trajectories.INSTANCE;
}
